---
title: "trmb-model"
format: pdf
editor: visual
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loadpackages}
library(minpack.lm)
library(ggplot2)
library(tidyverse)
library(knitr)
library(Stat2Data)
library(growthcurver)
library(epifitter)
library(nlstools)
library(nlsMicrobio)
library(easynls)
```

```{r import-data}
library(readxl)
trmb_data <- read_excel("~/Desktop/data+/20181214_trmB_all_data.xlsx")
trmb_meta <- read_excel("~/Desktop/data+/20181214_meta_trmB_all.xlsx")
```

```{r}
ggplot(trmb_data, aes(x = Time, y = blank_glu)) +
  geom_point()

ggplot(trmb_data, aes(x = Time, y = blank_noGlu)) +
  geom_point()
```

```{r logistic-model-1}
gc_fit_1 <- SummarizeGrowth(trmb_data$Time, log(trmb_data$blank_glu))
gc_fit_1
```

```{r plot-1}
plot(gc_fit_1)
str(gc_fit_1$vals)
```

```{r}
gc_fit_2 <- SummarizeGrowth(trmb_data$Time, log(trmb_data$blank_noGlu))
gc_fit_2
plot(gc_fit_2)
str(gc_fit_2$vals)
```

```{r}
gc_fit_3 <- SummarizeGrowth(trmb_data$Time, log(trmb_data$s287_trmb_nov10_glu))
gc_fit_3
plot(gc_fit_3)
str(gc_fit_3$vals)
```

```{r}
gc_fit_4 <- SummarizeGrowth(trmb_data$Time, log(trmb_data$s187_trmbHA_glu))
gc_fit_4
plot(gc_fit_4)
str(gc_fit_4$vals)
```

```{r}
gc_fit_5 <- SummarizeGrowth(trmb_data$Time, log(trmb_data$s187_trmbHA_glu2))
gc_fit_5
plot(gc_fit_5)
str(gc_fit_5$vals)
```

```{r}
gc_fit_6 <- SummarizeGrowth(trmb_data$Time, log(trmb_data$"6"))
gc_fit_6
plot(gc_fit_6)
str(gc_fit_6$vals)
```

```{r}
gc_fit_7 <- SummarizeGrowth(trmb_data$Time, log(trmb_data$s290_trmb_ptrmb__nov10_glu))
gc_fit_7
plot(gc_fit_7)
str(gc_fit_7$vals)
```

```{r}
gc_fit_8 <- SummarizeGrowth(trmb_data$Time, log(trmb_data$s289_trmb_ptrmbHA_nov10_glu))
gc_fit_8
plot(gc_fit_8)
str(gc_fit_8$vals)
```

```{r gompertz}
test <- read_excel("~/Desktop/data+/Book1.xlsx")
#test[colnames(test)[2]] = log(test[colnames(test)[2]])
model_gom = nlsfit(test, model = 10, start = c(a = 1.466, b = 0.132, c = 0.1))
model_gom
nlsplot(data.frame(test), model = 10, start = c(a = 1.466, b = 0.132, c = 0.1), xlab = "Time", ylab = "Growth", position = 1)
```

```{r logistic}
model_gom = nlsfit(test, model = 7, start = c(a = 1.4, b = 4.5, c = 0.2))
model_gom
nlsplot(data.frame(test1), model = 7, start = c(a = 1.4, b = 0.1, c = 0.3), xlab = "Time", ylab = "Growth", position = 1)
```


```{r}
trmb_meta %>%
  group_by(condition) %>%
  count()

trmb_meta %>%
  group_by(strain) %>%
  count()

trmb_meta %>%
  group_by(name) %>%
  count()

trmb_meta %>%
  group_by(media) %>%
  count()

trmb_meta %>%
  drop_na(name) %>%
  filter(name != "blank") %>%
  group_by(name) %>%
  count()
```

```{r}
wrangled <- trmb_meta %>%
  drop_na(name) %>%
  filter(name != "blank") %>%
  group_by(condition, media, name, biorep, techrep, variable) %>%
  count()

blank <- trmb_meta %>%
  filter(name == "blank") %>%
  arrange(condition, media)

wrangled <- wrangled %>%
  select(!n)

wrangled$index <- 1:nrow(wrangled)

sorted_wrangled <- wrangled %>%
  mutate(variable = as.numeric(variable)) %>%
  arrange(variable)

data_merge <- sorted_wrangled %>%
  group_by(variable, index) %>%
  select(variable, index)
```

```{r}
as.data.frame(t(data_merge))
```


```{r}
trmb_data2 <- trmb_data
trmb_data2[nrow(trmb_data) + 1,] <- NA
trmb_data2


dummy = 0
for(value in wrangled$variable){
  
  dummy = dummy + 1
}
```

```{r tries}
wrangled_with_blank <- trmb_meta %>%
  drop_na(name) %>%
  group_by(condition, media, name, biorep, techrep, variable) %>%
  count()

wrangled_with_blank <- wrangled_with_blank %>%
  select(!n)

wrangled_with_blank$index <- 1:nrow(wrangled_with_blank)

sorted_wrangled_w_blank <- wrangled_with_blank %>%
  mutate(variable = as.numeric(variable)) %>%
  arrange(variable)

data_merge_w_blank <- sorted_wrangled_w_blank %>%
  group_by(variable, index) %>%
  select(variable, index)
```


```{r}
trmb_flip <- as.data.frame(t(trmb_data))
index <- c(0)
index <- c(index, data_merge_w_blank$index)
trmb_flip['index'] <- index

trmb_flip <- trmb_flip %>%
  arrange(index) %>%
  select (!index)

trmb_df <- as.data.frame(t(trmb_flip))
  

#combined <- left_join(trmb_flip, data_merge_w_blank)
```

```{r}
wrangled_with_blank %>%
  group_by(condition, media, name) %>%
   count()
```
```{r}
wrangled_with_blank <- wrangled_with_blank %>% 
  add_column(new_name = NA)
```

```{r}
# 3*biorep + techrep - 3

renamed_meta <- unite(wrangled_with_blank, condition, media, name, col = "new_name", sep = "_")

renamed_meta <- renamed_meta %>% 
  mutate(number = 3*biorep + techrep - 3)

renamed_meta <- unite(renamed_meta, new_name, number, col = "new_name", sep = "_")
```

```{r}
trmb_flip <- as.data.frame(t(trmb_data))
index <- c(0)
index <- c(index, data_merge_w_blank$index)
trmb_flip['index'] <- index

trmb_flip <- trmb_flip %>%
  arrange(index) %>%
  select (!index)

renamed <- c(0)
renamed <- c(renamed, renamed_meta$new_name)
trmb_flip['renamed'] <- renamed

trmb_df_final <- as.data.frame(t(trmb_flip))
```

```{r}
new_col = c("Time")
new_col = c("Time", trmb_df_final[nrow(trmb_df_final), ][-1])
colnames(trmb_df_final) = new_col
```

```{r}
n<-dim(trmb_df_final)[1]
trmb_df_final<-trmb_df_final[1:(n-1),]
```

```{r graph-data}
trmb_fit_1 <- SummarizeGrowth(as.numeric(trmb_df_final$Time), log(as.numeric(trmb_df_final$`glu01_HvCa+ura50__trmB_1`)))
trmb_fit_1
plot(trmb_fit_1)
str(trmb_fit_1$vals)
```
```{r}
trmb_fit_2 <- SummarizeGrowth(as.numeric(trmb_df_final$Time), log(as.numeric(trmb_df_final$`glu01_HvCa+ura50__trmB_9`)))
plot(trmb_fit_1)
```

```{r}
example_1 <- trmb_df_final %>%
  select(Time, `glu01_HvCa+ura50__trmB_1`, `glu01_HvCa+ura50__trmB_2`, `glu01_HvCa+ura50__trmB_3`, `glu01_HvCa+ura50__trmB_4`, `glu01_HvCa+ura50__trmB_5`, `glu01_HvCa+ura50__trmB_6`, `glu01_HvCa+ura50__trmB_7`, `glu01_HvCa+ura50__trmB_8`, `glu01_HvCa+ura50__trmB_9`)
```

```{r}
test_graph <- pivot_longer(example_1, cols = 2:10, names_to ="type",
 values_to = "growth")
```

```{r}
ggplot(test_graph, aes(x = as.numeric(Time), y = as.numeric(growth), color = type)) +
  geom_point()
```


```{r}
example_1$bio_1_average <- rowMeans(example_1[ , c(2,3,4)], na.rm=TRUE)
example_1$bio_2_average <- rowMeans(example_1[ , c(5,6,7)], na.rm=TRUE)
example_1$bio_3_average <- rowMeans(example_1[ , c(8,9,10)], na.rm=TRUE)
example_1 <- example_1 %>%
  select(Time, bio_1_average, bio_2_average, bio_3_average)
```

```{r}
example_1_graph <- pivot_longer(example_1, cols = 2:4, names_to ="type",
 values_to = "growth")
```

```{r}
ggplot(example_1_graph, aes(x = Time, y = growth, color = type)) +
  geom_point()
```






